### ISSUE TITLE
Klio get reformats klio.yaml  (develop branch)  

### ISSUE THREAD

**Issue by Goorsky1** [g2a-com/klio#60]
1. Running `klio get` on such a `klio.yaml`:
```yaml
defaultRegistry: https://example/registry.yaml
dependencies:
  build:
    version: 1.6.0
  deploy:
    version: 0.12.0
  scripts:
    version: 0.5.0
```
Reformats it into:
```yaml
defaultRegistry: ""
dependencies:
  build:
    registry: https://example/registry.yaml
    version: 1.6.0
  deploy:
    registry: https://example/registry.yaml
    version: 0.12.0
  scripts:
    registry: https://example/registry.yaml
    version: 0.5.0

```
2. Running `klio get command` without `--from` flag ends up with an error:
`Failed to install command@*: Get "": unsupported protocol scheme ""`

Attempting to fix these issues like [this](https://github.com/Goorsky1/klio/compare/develop...Goorsky1:klio:test) seems to fix them however after it, running `klio get build` on such a `klio.yaml`:
```yaml
defaultRegistry:  https://example/registry.yaml
dependencies:
  build:
    registry:  https://example-nightly/registry.yaml
    version: 1.7.2
  deploy:
    version: 0.12.0
  scripts:
    version: 0.5.0
```
it gets reformatted to 
```yaml
defaultRegistry:  https://example/registry.yaml
dependencies:
  build:
    version: 1.7.2
  deploy:
    version: 0.12.0
  scripts:
    version: 0.5.0
```
and build gets downloaded from the default registry instead of the specified one
